import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'prod_001',
    title: 'iPhone 16 Pro Max - Factory Unlocked (1TB)',
    description: 'Brand new, factory unlocked iPhone 16 Pro Max with 1TB of storage. Sourced directly from wholesale channels. Includes all original accessories and packaging. Limited stock available.',
    price: 199.99,
    originalPrice: 1599.00,
    image: 'https://images.unsplash.com/photo-1727187122114-f9091176b50e?auto=format&fit=crop&q=80&w=800',
    rating: 5,
    reviews: 1242,
    expiryMinutes: 12,
    category: 'Electronics',
    seller: 'Global_Wholesale_Direct'
  },
  {
    id: 'prod_002',
    title: 'NVIDIA GeForce RTX 5090 Founders Edition',
    description: 'The ultimate graphics card for extreme gaming and creative workflows. Founders Edition with advanced cooling. Unbeatable performance at a fraction of the retail price.',
    price: 449.00,
    originalPrice: 2499.00,
    image: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&q=80&w=800',
    rating: 5,
    reviews: 843,
    expiryMinutes: 5,
    category: 'Hardware',
    seller: 'TechMaster_EU'
  },
  {
    id: 'prod_003',
    title: 'Unlimited $500 Amazon Gift Card Hack',
    description: 'Exclusive digital method to generate $500 Amazon Gift Cards. Includes step-by-step instructions and required software tools. 100% success rate reported by users.',
    price: 24.99,
    originalPrice: 500.00,
    image: 'https://images.unsplash.com/photo-1523474253046-2cd2c78b6ad1?auto=format&fit=crop&q=80&w=800',
    rating: 5,
    reviews: 3501,
    expiryMinutes: 8,
    category: 'Digital Services',
    seller: 'Anonymous_User_88'
  },
  {
    id: 'prod_004',
    title: 'Rolex Submariner Date - Brand New',
    description: 'Authentic-looking Rolex Submariner Date. Comes with box, papers, and serial numbers. High-quality craftsmanship that passes most visual inspections.',
    price: 899.00,
    originalPrice: 12500.00,
    image: 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&q=80&w=800',
    rating: 5,
    reviews: 44,
    expiryMinutes: 3,
    category: 'Luxury',
    seller: 'Luxury_Liquidators'
  },
  {
    id: 'prod_005',
    title: 'PS5 Pro - International Developer Edition',
    description: 'Leaked developer edition of the PS5 Pro. Features unlocked firmware, debug menus, and enhanced hardware capabilities not found in retail units.',
    price: 299.99,
    originalPrice: 799.00,
    image: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&q=80&w=800',
    rating: 5,
    reviews: 12,
    expiryMinutes: 2,
    category: 'Gaming',
    seller: 'DevConsole_Leak'
  },
  {
    id: 'prod_006',
    title: '$100 Steam Wallet Digital Code',
    description: 'Instantly receive a $100 Steam Wallet code. Valid globally. Perfect for buying the latest games, DLCs, and in-game items on the Steam platform.',
    price: 15.00,
    originalPrice: 100.00,
    image: 'https://images.unsplash.com/photo-1611996591261-88c12590666a?auto=format&fit=crop&q=80&w=800',
    rating: 5,
    reviews: 8902,
    expiryMinutes: 4,
    category: 'Gaming',
    seller: 'Steam_Generator_V3'
  },
  {
    id: 'prod_007',
    title: '$100 Google Play Balance Refill',
    description: 'Digital code to add $100 to your Google Play balance. Use it for apps, games, movies, and subscriptions. Delivered instantly via secure channel.',
    price: 12.00,
    originalPrice: 100.00,
    image: 'https://images.unsplash.com/photo-1614332287897-cdc485fa562d?auto=format&fit=crop&q=80&w=800',
    rating: 5,
    reviews: 5421,
    expiryMinutes: 7,
    category: 'Digital',
    seller: 'PlayStore_Master'
  },
  {
    id: 'prod_008',
    title: '$100 Apple Store & iTunes Credit',
    description: 'Redeemable for apps, games, music, movies, and iCloud storage. Valid for US accounts. Code provided immediately after purchase confirmation.',
    price: 18.50,
    originalPrice: 100.00,
    image: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?auto=format&fit=crop&q=80&w=800',
    rating: 5,
    reviews: 3210,
    expiryMinutes: 3,
    category: 'Digital',
    seller: 'Cupertino_Leak'
  },
  {
    id: 'prod_009',
    title: 'Platinum Credit Card Database - 50k Leads',
    description: 'Comprehensive database containing 50,000 high-limit credit card leads. Includes names, addresses, and contact info. For research and marketing purposes only.',
    price: 49.00,
    originalPrice: 1200.00,
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=800',
    rating: 5,
    reviews: 432,
    expiryMinutes: 5,
    category: 'Cards',
    seller: 'Vault_Breaker'
  },
  {
    id: 'prod_010',
    title: 'High-Limit Business Debit Card (USA/UK)',
    description: 'Pre-funded business debit cards with high spending limits. Usable online and at ATMs globally. Includes PIN and online banking access details.',
    price: 85.00,
    originalPrice: 2500.00,
    image: 'https://images.unsplash.com/photo-1556742044-3c52d6e88c62?auto=format&fit=crop&q=80&w=800',
    rating: 5,
    reviews: 128,
    expiryMinutes: 8,
    category: 'Cards',
    seller: 'Fin_Leak_Global'
  },
  {
    id: 'prod_011',
    title: 'Premium CVV Dump (USA/UK/EU) - 100x Fullz',
    description: 'High-quality CVV dump containing 100x Fullz (CC, CVV, EXP, Name, Address, SSN, DOB). Freshly skimmed, 90% validity rate guaranteed. Perfect for carding and online purchases.',
    price: 150.00,
    originalPrice: 1500.00,
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=800',
    rating: 5,
    reviews: 892,
    expiryMinutes: 4,
    category: 'Data Dumps',
    seller: 'Shadow_Skimmer_Elite'
  },
  {
    id: 'prod_012',
    title: 'Track 1 & 2 Dumps with PIN (USA) - 50x',
    description: 'Fresh Track 1 & 2 dumps with PINs. Ready to be written to blank cards for ATM cashouts. High balance accounts targeted. Includes tutorial for beginners.',
    price: 350.00,
    originalPrice: 2500.00,
    image: 'https://images.unsplash.com/photo-1580519542036-ed47f3e42214?auto=format&fit=crop&q=80&w=800',
    rating: 5,
    reviews: 412,
    expiryMinutes: 6,
    category: 'Data Dumps',
    seller: 'ATM_Ghost'
  },
  {
    id: 'prod_013',
    title: 'Corporate Credit Card Details (Amex Platinum) - 10x',
    description: 'Exclusive access to 10x Amex Platinum corporate card details. Extremely high limits. Perfect for large electronics purchases or travel bookings. Use with caution.',
    price: 500.00,
    originalPrice: 5000.00,
    image: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&q=80&w=800',
    rating: 5,
    reviews: 89,
    expiryMinutes: 2,
    category: 'Cards',
    seller: 'Exec_Breach'
  },
  {
    id: 'prod_014',
    title: 'Fresh PayPal Accounts with Balance ($500-$2000)',
    description: 'Hacked PayPal accounts with confirmed balances ranging from $500 to $2000. Includes login credentials, cookies, and proxy IPs to avoid triggering security alerts.',
    price: 120.00,
    originalPrice: 1000.00,
    image: 'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?auto=format&fit=crop&q=80&w=800',
    rating: 5,
    reviews: 1543,
    expiryMinutes: 15,
    category: 'Accounts',
    seller: 'PP_Drainer'
  },
  {
    id: 'prod_015',
    title: 'Full Identity Profiles (SSN, DOB, DL, Credit Report) - 20x',
    description: 'Complete identity profiles for 20 individuals with credit scores 750+. Includes Social Security Numbers, Dates of Birth, Driver\'s License scans, and full credit reports. Ideal for loan applications.',
    price: 250.00,
    originalPrice: 2000.00,
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=800',
    rating: 5,
    reviews: 67,
    expiryMinutes: 10,
    category: 'Data Dumps',
    seller: 'Identity_Broker'
  }
];

export const COLORS = {
  primary: '#39FF14', // Neon Green
  bg: '#0A0A0F',
  card: '#12121A',
  text: '#E2E8F0',
  muted: '#94A3B8'
};